---
controller:
  ingressClassResource:
    name: ingress-nginx
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
  watchIngressWithoutClass: true
  extraArgs:
    ingress-class: ingress-nginx

    # need the followings for a static IP
# apiVersion: approuting.kubernetes.azure.com/v1alpha1
# kind: NginxIngressController
# metadata:
#   name: nginx-static
# spec:
#   ingressClassName: nginx-static
#   controllerNamePrefix: nginx-static
#   loadBalancerAnnotations: 
#     service.beta.kubernetes.io/azure-pip-name: "myIngressPublicIP"
#     service.beta.kubernetes.io/azure-load-balancer-resource-group: "myNetworkResourceGroup"