apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secret-provider
  namespace: secret-test  # $keyVaultDemoNamespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: 0f4c03a4-847c-4c66-a9a4-8a68fbff0368 #$identityClientId      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: shachar-kv # $keyVaultName
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: secret1
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    tenantId: bd4f0481-b137-40f1-9e64-20cfd55fbf49 # $keyvaultTenantId           # The tenant ID of the key vault
  # secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  # - data:
  #   - key: examplesecretkey                           # data field to populate
  #     objectName: ExampleSecret                        # name of the mounted content to sync; this could be the object name or the object alias
  #   secretName: example-secret                     # name of the Kubernetes secret object
  #   type: Opaque